# Generated by Django 4.2.10 on 2025-09-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('img', models.ImageField(upload_to='indieapp/images/')),
                ('url_descargar', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_tres_populares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='indieapp/images/3_populares')),
                ('posicion', models.CharField(max_length=25)),
                ('fkidTrespopulares_idJuegos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indieapp.tbl_juegos')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_juegos',
            name='fkidJuegos_idMotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indieapp.tbl_motor'),
        ),
    ]
